#!/usr/bin/python

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--foo', help='foo help')
parser.print_help()
parser = argparse.ArgumentParser(prog='myprogram')
parser.print_help()
args = parser.parse_args()

parser.add_argument('--foo', help='foo of the %(prog)s program')
parser.print_help()




